"""Shared state schema passed through the LangGraph pipeline."""

from __future__ import annotations

from typing import Any, Literal, Optional
from langchain_core.messages import BaseMessage
from pydantic import BaseModel, ConfigDict, Field


TargetType = Literal["api", "web", "code"]


class QAState(BaseModel):
    """State that flows through every node in the QA agent graph."""

    # ── Input ─────────────────────────────────────────────────────────────────
    target: str = Field(description="URL, file path, or OpenAPI spec path provided by the user.")
    target_type: Optional[TargetType] = Field(
        default=None,
        description="Classified by the Orchestrator: 'api', 'web', or 'code'.",
    )
    test_strategy: str = Field(
        default="smoke",
        description="User-selected strategy for planning scope: smoke, sanity, regression, or custom.",
    )
    planning_notes: Optional[str] = Field(
        default=None,
        description="Optional user notes to influence generated test cases.",
    )
    project_name: str = Field(
        default="default",
        description="Logical project bucket for generated tests and historical test reuse.",
    )
    description_style: str = Field(
        default="standard",
        description="Test description style: standard or gherkin.",
    )
    run_with_existing_tests: bool = Field(
        default=False,
        description="When True, selected prior tests run alongside generated tests.",
    )
    existing_test_files: list[str] = Field(
        default_factory=list,
        description="Absolute paths to existing test files selected for combined execution.",
    )
    deduplicate_tests: bool = Field(
        default=True,
        description="When True, writer reuses existing project tests that appear duplicate.",
    )

    # ── Planner output ────────────────────────────────────────────────────────
    test_plan: Optional[str] = Field(
        default=None,
        description="Structured test plan produced by the Planner agent (markdown).",
    )

    # ── Writer output ─────────────────────────────────────────────────────────
    generated_tests: Optional[str] = Field(
        default=None,
        description="Raw Python test code produced by the Writer agent.",
    )
    test_file_path: Optional[str] = Field(
        default=None,
        description="Absolute path to the saved test file on disk.",
    )
    generated_test_files: list[str] = Field(
        default_factory=list,
        description="Absolute paths to generated/reused per-test files for this run.",
    )
    duplicate_reused: bool = Field(
        default=False,
        description="True when generated tests were replaced with an existing duplicate file.",
    )
    duplicate_source_path: Optional[str] = Field(
        default=None,
        description="Existing file path reused due to duplicate match.",
    )
    reuse_decisions: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Score-only reuse engine decision previews per generated case.",
    )
    coverage_gaps: list[str] = Field(
        default_factory=list,
        description="Approved case IDs that were not covered by generated/reused tests.",
    )
    coverage_guard_generated: list[str] = Field(
        default_factory=list,
        description="Case IDs where fallback tests were generated by coverage guard.",
    )

    # ── Executor output ───────────────────────────────────────────────────────
    execution_output: Optional[str] = Field(
        default=None,
        description="Combined stdout/stderr from running the test file.",
    )
    execution_success: Optional[bool] = Field(
        default=None,
        description="True if pytest exited with code 0.",
    )
    tests_passed: int = Field(default=0)
    tests_failed: int = Field(default=0)
    tests_errors: int = Field(default=0)

    # ── Reporter output ───────────────────────────────────────────────────────
    report: Optional[str] = Field(
        default=None,
        description="Markdown report summarising the full QA run.",
    )
    report_path: Optional[str] = Field(
        default=None,
        description="Path where the report was saved.",
    )

    # ── Pipeline metadata ─────────────────────────────────────────────────────
    self_heal: bool = Field(
        default=False,
        description="When True, failed tests are passed to the Healer agent before reporting.",
    )
    errors: list[str] = Field(
        default_factory=list,
        description="Non-fatal errors collected across agents.",
    )
    messages: list[BaseMessage] = Field(
        default_factory=list,
        description="Running message history available to each agent.",
    )

    model_config = ConfigDict(arbitrary_types_allowed=True)
