"""Writer agent — turns the test plan into runnable pytest code."""

from __future__ import annotations

import os
import uuid
from datetime import datetime
from pathlib import Path

from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage, HumanMessage

from agentic_qa.state import QAState


_SYSTEM_PROMPT = """You are the QA Test Writer in an autonomous multi-agent testing system.
You receive a test plan and produce complete, runnable pytest test code in Python.

Rules you MUST follow:
1. Output ONLY valid Python code — no markdown fences, no explanations.
2. Always import pytest at the top. Import httpx for API tests, playwright.sync_api for UI tests.
3. Each test case from the plan becomes a separate pytest test function named test_<id>_<snake_name>.
4. For API tests: use httpx.Client with a base_url fixture. Make real HTTP calls.
5. For web tests: use playwright sync API with a browser fixture (chromium, headless=True).
6. For code tests: import the module under test and write standard unit tests.
7. Include a module-level docstring: "# Generated by Agentic QA — {timestamp}"
8. Include a pytest fixture at the top for the target URL/path: TARGET = "{target}"
9. Every test must have at least one assert statement.
10. Add a brief comment above each test explaining what it validates.
11. Do NOT use unittest.TestCase — use plain pytest functions only.
12. Handle potential network errors gracefully (wrap in try/except where appropriate).

Target: {target}
Target type: {target_type}
"""


def write(state: QAState) -> dict:
    """Generate pytest test code from the test plan."""

    model = os.getenv("OPENAI_MODEL", "gpt-4o")
    llm = ChatOpenAI(model=model, temperature=0.1)

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    system = _SYSTEM_PROMPT.format(
        target=state.target,
        target_type=state.target_type,
        timestamp=timestamp,
    )

    messages = [
        SystemMessage(content=system),
        HumanMessage(content=f"Test Plan:\n\n{state.test_plan}"),
    ]

    response = llm.invoke(messages)
    code = _strip_markdown_fences(response.content)

    # Save generated test file
    reports_dir = Path(os.getenv("REPORTS_DIR", "./reports"))
    reports_dir.mkdir(parents=True, exist_ok=True)
    run_id = uuid.uuid4().hex[:8]
    test_file = reports_dir / f"generated_tests_{run_id}.py"
    test_file.write_text(code, encoding="utf-8")

    return {
        "generated_tests": code,
        "test_file_path": str(test_file.resolve()),
        "messages": state.messages + messages + [response],
    }


def _strip_markdown_fences(text: str) -> str:
    """Remove ```python ... ``` fences if the LLM included them."""
    lines = text.strip().splitlines()
    if lines and lines[0].startswith("```"):
        lines = lines[1:]
    if lines and lines[-1].startswith("```"):
        lines = lines[:-1]
    return "\n".join(lines)
